window.__ModuleLoader__.load({
  id: '@workstation/dsh-knowledge-base',
  factory: () => {
    const ACTIVE = 'data-dsh-knowledge-base-active'
    const VIEW = '[data-dsh-knowledge-base-view]'
    const ENTRY = '[data-dsh-knowledge-base-entry]'
    const EVENT = 'dsh-panel-activate'
    const PANEL = 'knowledge-base'
    const STYLE = 'dsh-knowledge-base-styles'
    const ICON = '<svg viewBox="0 0 16 16" width="14" height="14" fill="none" stroke="currentColor" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 2.5h10v11H3z"/><path d="M5 5h6M5 7.8h6M5 10.6h3.4"/><path d="M11.5 11.7l1.4 1.4"/></svg>'
    const CSS = `
[data-pane='conversation']{position:relative}[data-dsh-knowledge-base-view]{position:absolute;inset:0;display:none;z-index:62}html[data-dsh-knowledge-base-active] [data-dsh-knowledge-base-view]{display:block}html[data-dsh-knowledge-base-active] [data-pane='conversation']>:not([data-dsh-knowledge-base-view]){display:none!important}
.dsh-kb-entry{display:flex;align-items:center;gap:8px;width:100%;height:32px;padding:0 12px;background:transparent;border:0;border-radius:8px;color:var(--dsw-alias-label-secondary);cursor:pointer;font-size:13px;white-space:nowrap}.dsh-kb-entry:hover{background:var(--dsw-specific-sidebar-nav-item-hover);color:var(--dsw-alias-label-primary)}.dsh-kb-entry[data-active]{background:var(--dsw-specific-sidebar-nav-item-active);color:var(--dsw-alias-label-primary);font-weight:600}.dsh-kb-icon{display:inline-flex}[data-dsh-frame][data-sidebar-collapsed] .dsh-kb-entry{justify-content:center;padding:0}[data-dsh-frame][data-sidebar-collapsed] .dsh-kb-label{display:none}
.dsh-kb{height:100%;box-sizing:border-box;display:flex;flex-direction:column;gap:14px;padding:18px 20px;color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-base);font-family:var(--dsw-font-family,system-ui,sans-serif)}.dsh-kb-header{display:flex;gap:12px;align-items:center}.dsh-kb-heading{flex:1;min-width:0}.dsh-kb h1{margin:0;font-size:18px}.dsh-kb-sub{margin:4px 0 0;color:var(--dsw-alias-label-tertiary);font-size:12px}.dsh-kb-btn,.dsh-kb input,.dsh-kb select,.dsh-kb textarea{font:inherit;color:var(--dsw-alias-label-primary);background:var(--dsw-specific-input-major);border:1px solid var(--dsw-alias-border-l2);border-radius:8px}.dsh-kb-btn{padding:8px 11px;cursor:pointer;background:var(--dsw-alias-bg-layer-2)}.dsh-kb-search{width:min(34vw,340px);padding:8px 10px}.dsh-kb-main{min-height:0;flex:1;display:grid;grid-template-columns:minmax(260px,.85fr) minmax(390px,1.75fr);gap:14px}.dsh-kb-list,.dsh-kb-detail{overflow:auto;border:1px solid var(--dsw-alias-border-l1);border-radius:12px;background:var(--dsw-alias-bg-layer-2)}.dsh-kb-list{padding:8px;display:flex;flex-direction:column;gap:6px}.dsh-kb-card{padding:10px 11px;text-align:left;border:1px solid transparent;border-radius:9px;background:transparent;color:inherit;cursor:pointer}.dsh-kb-card:hover,.dsh-kb-card[data-selected]{background:var(--dsw-specific-sidebar-nav-item-hover);border-color:var(--dsw-alias-border-l2)}.dsh-kb-card-title{font-weight:600;font-size:13px}.dsh-kb-card-meta{margin-top:5px;font-size:11px;color:var(--dsw-alias-label-tertiary)}.dsh-kb-detail{padding:18px}.dsh-kb-detail h2{margin:0 0 8px;font-size:18px}.dsh-kb-detail p{line-height:1.6}.dsh-kb-meta{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.dsh-kb-tag{padding:3px 7px;border-radius:999px;background:var(--dsw-alias-bg-layer-3);font-size:11px;color:var(--dsw-alias-label-secondary)}.dsh-kb-content{white-space:pre-wrap;word-break:break-word;padding:12px;border:1px solid var(--dsw-alias-border-l1);border-radius:8px;background:var(--dsw-specific-input-major);font:12px/1.6 ui-monospace,Consolas,monospace}.dsh-kb-empty{padding:18px;color:var(--dsw-alias-label-tertiary);font-size:13px}.dsh-kb-tabs{display:flex;gap:7px}.dsh-kb-tabs button[data-active]{font-weight:700}.dsh-kb-form{display:flex;flex-direction:column;gap:10px;max-width:760px}.dsh-kb-form label{display:flex;flex-direction:column;gap:5px;font-size:12px;color:var(--dsw-alias-label-secondary)}.dsh-kb-form input,.dsh-kb-form select,.dsh-kb-form textarea{padding:8px}.dsh-kb-form textarea{min-height:260px;resize:vertical}.dsh-kb-note{font-size:12px;color:var(--dsw-alias-label-tertiary);line-height:1.55}.dsh-kb-status{padding:10px;border-radius:8px;background:var(--dsw-alias-bg-layer-3);font-size:12px}@media(max-width:850px){.dsh-kb-main{grid-template-columns:1fr}.dsh-kb-search{width:180px}}
`
    function el(tag, className, text) { const node = document.createElement(tag); if (className) node.className = className; if (text !== undefined) node.textContent = text; return node }
    function ensureStyle() { if (document.getElementById(STYLE)) return; const style = document.createElement('style'); style.id = STYLE; style.textContent = CSS; document.head.append(style) }
    function sidebarRoot() { const column = document.querySelector('[data-pane="sidebar"], [class*="sidebarCol"]'); if (!column) return undefined; const owner = column.querySelector('[class*="logoRow"]')?.parentElement; return owner || column.firstElementChild || undefined }
    function newSessionButton(root) { return root.querySelector('button[class*="newSession"]') || Array.from(root.children).find(child => child.tagName === 'BUTTON') }
    function placeEntry(root, entry) { const button = newSessionButton(root); if (!button) return false; if (entry.parentElement !== root) { const row = button.closest('[class*="logoRow"]'); const base = row && row.parentElement === root ? row : button; const family = Array.from(root.children).filter(node => node instanceof HTMLElement && node.matches('[data-dsh-taskboard-entry], [data-dsh-ssh-entry], [data-dsh-skill-library-entry], [data-dsh-knowledge-base-entry]')); const anchor = family.length ? family[family.length - 1].nextElementSibling : base.nextElementSibling; root.insertBefore(entry, anchor) } return true }
    class App {
      constructor(){this.open=false;this.mode='browse';this.documents=[];this.raw=[];this.selected=undefined;this.query='';this.loading=false;this.error='';this.root=undefined;this.importStatus='';this.rawStatus=''}
      async load(){this.loading=true;this.error='';this.render();try{const r=await fetch('/api/knowledge-base/documents',{cache:'no-store'});const p=await r.json();if(!r.ok)throw new Error(p.error||'无法读取知识库');this.documents=Array.isArray(p.documents)?p.documents:[];if(!this.selected||!this.documents.some(d=>d.documentId===this.selected.documentId))this.selected=this.documents[0]}catch(e){this.error=e.message||String(e)}finally{this.loading=false;this.render()}}
      show(){this.open=true;this.emit();if(!this.documents.length&&!this.loading)this.load()};close(){this.open=false;this.emit()};toggle(){this.open?this.close():this.show()};emit(){this.onchange?.()}
      visible(){const q=this.query.trim().toLowerCase();return q?this.documents.filter(d=>[d.title,d.fileName,d.preview,d.space,d.project].join(' ').toLowerCase().includes(q)):this.documents}
      async loadRaw(){this.rawStatus='正在扫描 knowledge/raw/…';this.render();try{const r=await fetch('/api/knowledge-base/raw',{cache:'no-store'});const p=await r.json();if(!r.ok)throw new Error(p.error||'无法扫描 Raw 收件箱');this.raw=Array.isArray(p.files)?p.files:[];this.rawStatus=this.raw.length?`发现 ${this.raw.length} 个 raw 文件。`:'Raw 收件箱为空。将文件放入 knowledge/raw/ 后点击刷新。'}catch(e){this.rawStatus='扫描失败：'+(e.message||String(e))}this.render()}
      async select(doc){this.selected=doc;this.render();try{const r=await fetch('/api/knowledge-base/document?id='+encodeURIComponent(doc.documentId),{cache:'no-store'});const p=await r.json();if(!r.ok)throw new Error(p.error||'无法读取文档');this.selected=p.document;this.render()}catch(e){this.error=e.message||String(e);this.render()}}
      render(){const root=this.root;if(!root)return;root.replaceChildren();const frame=el('section','dsh-kb');const header=el('header','dsh-kb-header');const heading=el('div','dsh-kb-heading');heading.append(el('h1','', '知识库'),el('p','dsh-kb-sub',this.loading?'正在读取 Vault…':`语义记忆 · 已导入 ${this.documents.length} 份资料`));const tabs=el('div','dsh-kb-tabs');for(const [id,label] of [['browse','浏览'],['raw','Raw 收件箱'],['import','粘贴导入']]){const button=el('button','dsh-kb-btn',label);button.type='button';if(this.mode===id)button.dataset.active='';button.onclick=()=>{this.mode=id;this.render()};tabs.append(button)}const refresh=el('button','dsh-kb-btn','刷新');refresh.type='button';refresh.disabled=this.loading;refresh.onclick=()=>this.load();header.append(heading,tabs,refresh);frame.append(header);if(this.mode==='raw'){frame.append(this.renderRaw());root.append(frame);return}if(this.mode==='import'){frame.append(this.renderImport());root.append(frame);return}const search=el('input','dsh-kb-search');search.type='search';search.placeholder='搜索标题、来源、内容摘要…';search.value=this.query;search.oninput=()=>{this.query=search.value;this.render()};header.append(search);const main=el('div','dsh-kb-main');const list=el('div','dsh-kb-list');if(this.error)list.append(el('div','dsh-kb-empty','读取失败：'+this.error));const docs=this.visible();if(!this.error&&!docs.length)list.append(el('div','dsh-kb-empty',this.loading?'读取中…':'尚未导入资料。请使用“导入”开始。'));for(const doc of docs){const card=el('button','dsh-kb-card');card.type='button';if(this.selected?.documentId===doc.documentId)card.dataset.selected='';card.append(el('div','dsh-kb-card-title',doc.title),el('div','dsh-kb-card-meta',[doc.space,doc.project,doc.status].filter(Boolean).join(' · ')));card.onclick=()=>this.select(doc);list.append(card)}const detail=el('article','dsh-kb-detail');const d=this.selected;if(!d)detail.append(el('div','dsh-kb-empty','选择一份资料查看来源和原文。'));else{detail.append(el('h2','',d.title));const meta=el('div','dsh-kb-meta');for(const value of [`${d.space}${d.project?' / '+d.project:''}`,d.status,d.authority,d.sourceDescription||'本地导入'])meta.append(el('span','dsh-kb-tag',value));detail.append(meta,el('p','dsh-kb-note',`导入时间：${d.importedAt||'—'} · 文件：${d.fileName||d.path||'—'}`));detail.append(el('pre','dsh-kb-content',d.content||d.preview||'（文档内容不可用）'))}main.append(list,detail);frame.append(main);root.append(frame)}
      renderRaw(){const wrap=el('div','dsh-kb-detail');wrap.append(el('h2','', 'Raw 文档收件箱'),el('p','dsh-kb-note','请直接将大量原始 Markdown 或 UTF-8 文本文档放进工作站目录的 knowledge/raw/。Raw 文件在你点击“处理”前不会进入 agent 检索；成功后文件将移动到 documents/imported/ 并生成来源 manifest。P0 支持 .md 与 .txt，每个文件最多 2 MB。'));const refresh=el('button','dsh-kb-btn','扫描 Raw 目录');refresh.type='button';refresh.onclick=()=>this.loadRaw();wrap.append(refresh);const status=el('div','dsh-kb-status',this.rawStatus||'点击扫描以查看待处理文件。');wrap.append(status);const supported=this.raw.filter(file=>file.supported);if(this.raw.length){const form=el('form','dsh-kb-form');const title=el('input');title.placeholder='可选：批量处理时的统一标题前缀（建议留空）';const source=el('input');source.placeholder='可选：来源说明，例如 UX 资料集';const space=el('select');for(const value of ['foundations','shared-context','projects']){const opt=el('option','',value);opt.value=value;space.append(opt)}const project=el('input');project.placeholder='项目 ID（项目空间必填）';const list=el('div','dsh-kb-content');for(const file of this.raw){const label=el('label','');const check=el('input');check.type='checkbox';check.value=file.path;check.disabled=!file.supported;label.append(check,document.createTextNode(` ${file.path} · ${file.bytes} bytes · ${file.supported?'可处理':file.reason}`));list.append(label,document.createElement('br'))}const fields=[['统一标题（可选）',title],['来源说明（可选）',source],['知识空间',space],['项目 ID',project]];for(const [label,input] of fields){const field=el('label','',label);field.append(input);form.append(field)}const submit=el('button','dsh-kb-btn',`处理选中的 ${supported.length} 个文件`);submit.type='submit';form.append(list,submit);form.onsubmit=async event=>{event.preventDefault();const paths=Array.from(list.querySelectorAll('input[type="checkbox"]:checked')).map(input=>input.value);if(!paths.length){status.textContent='请至少选择一个可处理的 raw 文件。';return}submit.disabled=true;status.textContent='正在处理…';try{const r=await fetch('/api/knowledge-base/process-raw',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({paths,title:title.value,sourceDescription:source.value,space:space.value,project:project.value})});const p=await r.json();if(!r.ok)throw new Error(p.error||'处理失败');this.rawStatus=`已处理 ${p.processed.length} 个文件${p.failed.length?`；${p.failed.length} 个失败：${p.failed.map(x=>x.path+' '+x.error).join('；')}`:''}`;await this.load();await this.loadRaw()}catch(e){this.rawStatus='处理失败：'+(e.message||String(e));status.textContent=this.rawStatus;submit.disabled=false}};wrap.append(form)}return wrap}
      renderImport(){const wrap=el('div','dsh-kb-detail');wrap.append(el('h2','', '导入外部文档'),el('p','dsh-kb-note','P0 支持 UTF-8 Markdown 和纯文本。原件与 manifest 会写入 knowledge/documents/imported/ 和 manifests/；导入资料保持 imported 状态，不会自动成为用户定义。'));const form=el('form','dsh-kb-form');const title=el('input');title.required=true;const fileName=el('input');fileName.value='document.md';const source=el('input');source.placeholder='例如：产品设计基础教材，第 3 版';const space=el('select');for(const value of ['foundations','shared-context','projects']){const opt=el('option','',value);opt.value=value;space.append(opt)}const project=el('input');project.placeholder='project-id（仅项目空间必填，例如 game-project-a）';const content=el('textarea');content.required=true;content.placeholder='粘贴 Markdown 或 UTF-8 纯文本内容…';const labels=[['标题',title],['文件名',fileName],['来源说明',source],['知识空间',space],['项目 ID',project],['文档内容',content]];for(const [label,input] of labels){const field=el('label','',label);field.append(input);form.append(field)}const status=el('div','dsh-kb-status',this.importStatus||'导入后可在浏览页搜索和查看该资料。');const submit=el('button','dsh-kb-btn','确认导入');submit.type='submit';form.append(status,submit);form.onsubmit=async event=>{event.preventDefault();submit.disabled=true;status.textContent='正在保存导入资料…';try{const r=await fetch('/api/knowledge-base/import',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title:title.value,fileName:fileName.value,sourceDescription:source.value,space:space.value,project:project.value,content:content.value})});const p=await r.json();if(!r.ok)throw new Error(p.error||'导入失败');this.importStatus=`已导入：${p.document.title}（${p.document.documentId}）`;this.mode='browse';await this.load()}catch(e){this.importStatus='导入失败：'+(e.message||String(e));status.textContent=this.importStatus;submit.disabled=false}};wrap.append(form);return wrap}
    }
    function mount(app){ensureStyle();const entry=el('button','dsh-kb-entry');entry.type='button';entry.dataset.dshKnowledgeBaseEntry='';entry.setAttribute('aria-label','知识库');entry.title='知识库';entry.innerHTML='<span class="dsh-kb-icon">'+ICON+'</span><span class="dsh-kb-label">知识库</span>';entry.onclick=()=>app.toggle();let sidebar;const observer=new MutationObserver(()=>{sidebar=sidebar?.isConnected?sidebar:sidebarRoot();if(sidebar)placeEntry(sidebar,entry)});observer.observe(document.body,{childList:true,subtree:true});sidebar=sidebarRoot();if(sidebar)placeEntry(sidebar,entry);let container;const viewObserver=new MutationObserver(()=>{if(container?.isConnected)return;const pane=document.querySelector('[data-pane="conversation"]');if(!pane)return;container=el('div');container.dataset.dshKnowledgeBaseView='';pane.append(container);app.root=container;app.render()});viewObserver.observe(document.body,{childList:true,subtree:true});const update=()=>{if(app.open){document.documentElement.removeAttribute('data-dsh-skill-library-active');document.documentElement.removeAttribute('data-dsh-taskboard-active');document.documentElement.removeAttribute('data-dsh-ssh-active');document.documentElement.setAttribute(ACTIVE,'');entry.dataset.active='';document.dispatchEvent(new CustomEvent(EVENT,{detail:PANEL}))}else{document.documentElement.removeAttribute(ACTIVE);delete entry.dataset.active}};app.onchange=update;document.addEventListener(EVENT,event=>{if(event.detail!==PANEL&&app.open)app.close()});document.addEventListener('click',event=>{const target=event.target instanceof Element?event.target:null;if(app.open&&target?.closest('[class*="sessionRow"],[class*="projectRow"],[class*="newSession"]'))app.close()},true);update();return()=>{observer.disconnect();viewObserver.disconnect();entry.remove();container?.remove();document.documentElement.removeAttribute(ACTIVE)}}
    const module={exports:{}};module.exports.apply=()=>mount(new App());module.exports.inject=[];return module.exports
  }
})
